package com.nexora.payment.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Core payment record. Each time a user initiates a checkout
 * across any Nexora service, a Payment entry is created here.
 */
@Entity
@Table(name = "payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Composite reference in the form "{service}:{orderId}",
     * e.g. "marketplace:42" or "food:17".
     * Allows payment-service to trace back to originating service.
     */
    @Column(name = "order_id", nullable = false)
    private String orderId;

    /** Keycloak userId of the payer */
    @Column(name = "payer_id", nullable = false)
    private String payerId;

    /** Keycloak userId of the payee/merchant (if applicable, null for platform payments) */
    @Column(name = "payee_id")
    private String payeeId;

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    /** ISO-4217 currency code */
    @Column(nullable = false, length = 3)
    @Builder.Default
    private String currency = "BDT";

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;

    /** Unique transaction reference generated by this gateway */
    @Column(name = "transaction_id", unique = true, nullable = false)
    private String transactionId;

    /** Method used for this payment */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false)
    private PaymentMethodType paymentMethod;

    /**
     * For NEXORA_WALLET payments: the wallet transaction ID that debited the payer.
     * Useful for reconciliation and refund flows.
     */
    @Column(name = "wallet_transaction_id")
    private Long walletTransactionId;

    /**
     * For non-wallet methods: an external reference (e.g. bKash TrxID,
     * bank transfer ref) entered by the user for manual verification.
     */
    @Column(name = "external_reference", length = 200)
    private String externalReference;

    /** Optional note from the service or admin */
    @Column(length = 500)
    private String note;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (status == null) status = PaymentStatus.PENDING;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
