spring.application.name=demo

# Server configuration
server.port=8082

# Keycloak Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/nexora
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/nexora/protocol/openid-connect/certs

# Custom properties for security converter
jwt.auth.converter.resource-id=nexora-client
jwt.auth.converter.principal-attribute=preferred_username

# Enable detailed security logging for development
logging.level.org.springframework.security=DEBUG
